gaurav-nelson/github-action-markdown-link-check

- README.md
> Example correction

- README.md
- entrypoint.sh
- mlc_config.json
Support for https://github.com/tcort/markdown-link-check#config-file-format
> Added support for markdown-link-check config file

- action.yml
Based on https://help.github.com/en/articles/creating-a-docker-container-action
> Added actions.yml

- Dockerfile
- README.md
- README2.md
- action.yml
- entrypoint.sh
> Enable quite and verbose modes

- .github/workflows/push.yml
- entrypoint.sh
- md/md-level-1/level-1a.md
- md/md-level-1/level-1b.md
- md/md-level-1/md-level-2/level-2a.md
- md/md-level-1/md-level-2/level-2b.md
- Fixes `maxdepth` predicate use. (`-maxdepth` instead of `--maxdepth`)
- moves `maxdepth` at correct place in the final command
- uses bash array to run the command, instead of `eval`
- Added files to check if 'maxdepth` works.
> Maxdepth variable fix

- .github/workflows/push.yml
- Dockerfile
- README.md
- action.yml
- entrypoint.sh
- md/file1.md
- md/file2.md
> Modified files check

- .github/workflows/push.yml
- README.md
- action.yml
- entrypoint.sh
- md/file3.markdown
- md/file4.markdown
> Support file extension configuration

- .github/workflows/push.yml
- entrypoint.sh
This reverts commit 6bb80c4487a3ec6bdf24f2fd9b4dcbecf4ed540d.
Temp fixes for #40 and #45
> Revert "Cleanup output for -q option"

- .github/workflows/push.yml
- entrypoint.sh
> Fix file extension bug

- entrypoint.sh
> Fixed file extension check bug

- entrypoint.sh
> File extension check fix

- entrypoint.sh
Remove extension output text (not required as .md is default)
> Remove extension output text (not required as .md is default)

- entrypoint.sh
> modified files exten fix

- entrypoint.sh
> Check if files and dirs exist

- entrypoint.sh
Updated markdown-link-check to version: 3.8.3
> Dependency update

- entrypoint.sh
- md/file1.md
Please feel free to change the URLs and rearrange the tests according to your design.
> update dep version

- .github/workflows/push.yml
- entrypoint.sh
- md/AdditionalFileTest1.md
- md/AdditionalFileTest2.md
Missed one more case from #88.
> Fix more file path quoting issues

- Dockerfile
Updates the base image to the latest Long Term Suport that is more stable
> Changes base image to LTS

- entrypoint.sh
fix issue https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132
> Fixed unsafe repository

- entrypoint.sh
Adds a command to list installed node module versions to help in debugging the issues that show up because of the changes in the underlying node modules.
> List installed node module versions

- README.md
This PR adds an example to the documentation to describe the nature of inputs and outputs
It resolves #124
> docs: added example to README.md

- entrypoint.sh
> Fully disable the Git ownership check

- action.yml
I was parsing the markdown and the library I use threw an error. I don't think it's valid markdown, so I thought I'd propose a fix.
> Fix markdown setup

- entrypoint.sh
> Update dependency version
